HouseRentingSystem.Web/Areas/Admin/Controllers/HousesController.cs
using HouseRentingSystem.Services.Agents;
using HouseRentingSystem.Services.Houses;
using HouseRentingSystem.Web.Areas.Admin.Models;
using HouseRentingSystem.Web.Infrastructure;
using Microsoft.AspNetCore.Mvc;

namespace HouseRentingSystem.Web.Areas.Admin.Controllers
{
    public class HousesController : AdminController
    {
        private readonly IHouseService houses;
        private readonly IAgentService agents;

        public HousesController(IHouseService houses,
            IAgentService agents)
        {
            this.houses = houses;
            this.agents = agents;
        }

        public IActionResult Mine()
        {
            var myHouses = new MyHousesViewModel();

            var adminUserId = this.User.Id();
            myHouses.RentedHouses = this.houses.AllHousesByUserId(adminUserId);

            var adminAgentId = this.agents.GetAgentId(adminUserId);
            myHouses.AddedHouses = this.houses.AllHousesByAgentId(adminAgentId);

            return View(myHouses);
        }
    }
}

HouseRentingSystem.Web/Areas/Admin/Controllers/RentsController.cs
using HouseRentingSystem.Services.Rents;
using HouseRentingSystem.Services.Rents.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

using static HouseRentingSystem.Web.Areas.Admin.AdminConstants;

namespace HouseRentingSystem.Web.Areas.Admin.Controllers
{
    public class RentsController : AdminController
    {
        private readonly IRentService rents;
        private readonly IMemoryCache cache;

        public RentsController(IRentService rents,
            IMemoryCache cache)
        {
            this.rents = rents;
            this.cache = cache;
        }



        [Route("Rents/All")]
        public IActionResult All()
        {
            var rents = this.cache
                .Get<IEnumerable<RentServiceModel>>(RentsCacheKey);

            if (rents == null)
            {
                rents = this.rents.All();

                var cacheOptions = new MemoryCacheEntryOptions()
                   .SetAbsoluteExpiration(TimeSpan.FromMinutes(5));

                this.cache.Set(RentsCacheKey, rents, cacheOptions);
            }

            return View(rents);
        }
    }
}

HouseRentingSystem.Web/Areas/Admin/Controllers/UsersController.cs
using HouseRentingSystem.Services.Users.Models;
using HouseRentingSystem.Services.Users;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

using static HouseRentingSystem.Web.Areas.Admin.AdminConstants;
namespace HouseRentingSystem.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        private readonly IUserService users;
        private readonly IMemoryCache cache;

        public UsersController(IUserService users,
            IMemoryCache cache)
        { 
            this.users = users;
            this.cache = cache;
        }


        [Route("Users/All")]
        public IActionResult All()
        {
            var users = this.cache
                .Get<IEnumerable<UserServiceModel>>(UsersCacheKey);

            if (users == null)
            {
                users = this.users.All();

                var cacheOptions = new MemoryCacheEntryOptions()
                   .SetAbsoluteExpiration(TimeSpan.FromMinutes(5));

                this.cache.Set(UsersCacheKey, users, cacheOptions);
            }

            return View(users);
        }
    }
}

HouseRentingSystem.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@inject IAgentService agents

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Best House Renting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HouseRentingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">House Renting Worldwide</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <div>
                                <a class="btn dropdown-toggle" href="#" role="button"
                                   id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    All
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    <li>
                                        <a class="dropdown-item nav-link text-dark" asp-area=""
                                           asp-controller="Houses" asp-action="All">All Houses</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item nav-link text-dark" asp-area=""
                                           asp-controller="Rents" asp-action="All">All Rents</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item nav-link text-dark" asp-area=""
                                           asp-controller="Users" asp-action="All">All Users</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Houses" asp-action="Mine">My Houses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Houses" asp-action="Add">Add House</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData["message"] != null)
            {
                <div class="alert alert-success alert-dismissible fade show"
                 role="alert">
                    @TempData["message"]
                    <button type="button" class="btn-close"
                        data-bs-dismiss="alert"
                        aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - HouseRentingSystem
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>